-- Insert Test Employer Users
INSERT INTO users (name, email, role, password, email_verified_at, created_at, updated_at) VALUES
('TechCorp Philippines', 'techcorp@example.com', 'employer', '$2y$12$xxxxxxxxxxxxxxxxxxx', NOW(), NOW(), NOW()),
('StartUp Innovations Inc', 'startup@example.com', 'employer', '$2y$12$xxxxxxxxxxxxxxxxxxx', NOW(), NOW(), NOW());

-- Insert Verified Company Profile
INSERT INTO company_profiles (
    user_id,
    company_name,
    business_name,
    trade_name,
    established_year,
    office_type,
    employer_type_detail,
    workforce_size,
    tin,
    line_of_business,
    street_village,
    barangay,
    city_municipality,
    province,
    establishment_contact_person,
    establishment_contact_position,
    establishment_email,
    establishment_phone,
    contact_person_name,
    contact_person_phone,
    business_permit_path,
    dti_sec_registration_path,
    verification_status,
    verification_notes,
    verified_at,
    verified_by,
    created_at,
    updated_at
) VALUES (
    1,
    'TechCorp Philippines',
    'TechCorp Phil Inc',
    'TECH-PH',
    2015,
    'main_office',
    'direct_hire',
    'large',
    '123456789012',
    'Information Technology and Software Development',
    '123 Business Park Avenue',
    'Fort Bonifacio',
    'Taguig',
    'Metro Manila',
    'Juan dela Cruz',
    'President',
    'techcorp@example.com',
    '+63-2-1234-5678',
    'Maria Santos',
    '+63-917-123-4567',
    'storage/company-docs/techcorp_permit.pdf',
    'storage/company-docs/techcorp_dti.pdf',
    'verified',
    'Company verified on 2026-05-01. All documents submitted and validated.',
    '2026-05-01 10:30:00',
    1,
    NOW(),
    NOW()
);

-- Insert Pending Company Profile
INSERT INTO company_profiles (
    user_id,
    company_name,
    business_name,
    trade_name,
    established_year,
    office_type,
    employer_type_detail,
    workforce_size,
    tin,
    line_of_business,
    street_village,
    barangay,
    city_municipality,
    province,
    establishment_contact_person,
    establishment_contact_position,
    establishment_email,
    establishment_phone,
    contact_person_name,
    contact_person_phone,
    business_permit_path,
    dti_sec_registration_path,
    verification_status,
    verification_notes,
    created_at,
    updated_at
) VALUES (
    2,
    'StartUp Innovations Inc',
    'StartUp Innovations Incorporated',
    'STARTUP-INC',
    2021,
    'main_office',
    'local_recruitment',
    'small',
    '987654321098',
    'Business Process Outsourcing and Digital Solutions',
    '456 Innovation Drive',
    'Makati',
    'Makati',
    'Metro Manila',
    'Robert Gonzales',
    'CEO',
    'startup@example.com',
    '+63-2-9876-5432',
    'Angela Lopez',
    '+63-918-987-6543',
    'storage/company-docs/startup_permit.pdf',
    'storage/company-docs/startup_dti.pdf',
    'pending',
    NULL,
    NOW(),
    NOW()
);
