<?php

namespace App\Services;

use App\Models\PesoClearance;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Str;

class PesoClearanceService
{
    /**
     * Automatically create a PESO clearance for a new jobseeker
     */
    public function createAutoForJobseeker(User $user): ?PesoClearance
    {
        // Only create for jobseekers
        if ($user->role !== 'jobseeker') {
            return null;
        }

        // Check if already has a clearance
        if ($user->pesoClearances()->exists()) {
            return null;
        }

        $clearanceCount = PesoClearance::query()
            ->where('user_id', $user->id)
            ->count();

        return PesoClearance::create([
            'user_id' => $user->id,
            'request_date' => now(),
            'clearance_number' => 'AUTO-' . now()->format('YmdHis') . '-' . str_pad((string) ($clearanceCount + 1), 3, '0', STR_PAD_LEFT),
            'issue_date' => null,
            'expiry_date' => null,
            'status' => 'pending',
            'remarks' => 'Auto-generated clearance for new jobseeker',
            'is_first_time_jobseeker' => true,
        ]);
    }

    /**
     * Generate PESO clearances for multiple jobseekers
     */
    public function generateForMultipleJobseekers(array $userIds): array
    {
        $created = [];
        $skipped = [];

        foreach ($userIds as $userId) {
            $user = User::find($userId);

            if (!$user || $user->role !== 'jobseeker') {
                $skipped[] = $userId;
                continue;
            }

            if ($user->pesoClearances()->exists()) {
                $skipped[] = $userId;
                continue;
            }

            $clearance = $this->createAutoForJobseeker($user);
            if ($clearance) {
                $created[] = $clearance->id;
            }
        }

        return [
            'created' => $created,
            'skipped' => $skipped,
            'count' => count($created),
        ];
    }

    /**
     * Generate clearances for all jobseekers without one
     */
    public function generateForAllJobseekers(): array
    {
        $jobseekerIds = User::query()
            ->where('role', 'jobseeker')
            ->whereDoesntHave('pesoClearances')
            ->pluck('id')
            ->toArray();

        return $this->generateForMultipleJobseekers($jobseekerIds);
    }

    /**
     * Issue a clearance with auto-generated details
     */
    public function issueAutoGeneratedClearance(PesoClearance $clearance, ?string $remarks = null): bool
    {
        if ($clearance->status !== 'pending') {
            return false;
        }

        $clearance->update([
            'status' => 'active',
            'clearance_number' => 'CLR-' . now()->format('YmdHis') . '-' . $clearance->id,
            'issue_date' => now(),
            'expiry_date' => now()->addYear(),
            'remarks' => $remarks ?? 'PESO clearance auto-issued by admin',
        ]);

        return true;
    }

    /**
     * Get clearance statistics
     */
    public function getStatistics(): array
    {
        return [
            'total_clearances' => PesoClearance::count(),
            'pending_clearances' => PesoClearance::where('status', 'pending')->count(),
            'active_clearances' => PesoClearance::where('status', 'active')->count(),
            'expired_clearances' => PesoClearance::where('status', 'expired')
                ->orWhere('expiry_date', '<', now())
                ->count(),
            'jobseekers_without_clearance' => User::query()
                ->where('role', 'jobseeker')
                ->whereDoesntHave('pesoClearances')
                ->count(),
        ];
    }
}
