<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Chatbot Topic Filter
    |--------------------------------------------------------------------------
    |
    | These words/phrases are used to decide whether the chatbot should respond.
    | Keep them aligned with actual PESO Job Portal features.
    |
    */

    'allowed_topics' => [
        // Account / Authentication
        'account',
        'make account',
        'make an account',
        'create account',
        'create an account',
        'account creation',
        'register',
        'registration',
        'sign up',
        'signup',
        'enroll',
        'log in',
        'login',
        'sign in',
        'signin',
        'logout',
        'log out',
        'forgot password',
        'reset password',
        'change password',
        'update password',
        'password recovery',
        'email verification',
        'verify email',
        'account verification',
        'verify my account',
        'verification code',
        'otp',

        // Profile / Resume
        'profile',
        'user profile',
        'profile update',
        'update profile',
        'edit profile',
        'personal information',
        'contact information',
        'address',
        'work experience',
        'experience',
        'skills',
        'education',
        'resume',
        'cv',
        'curriculum vitae',
        'upload resume',
        'upload cv',
        'resume upload',

        // Job Listings / Search
        'job',
        'jobs',
        'job listing',
        'job listings',
        'job vacancy',
        'job vacancies',
        'vacancy',
        'vacancies',
        'available jobs',
        'latest jobs',
        'job search',
        'search jobs',
        'find jobs',
        'browse jobs',
        'filter jobs',
        'job details',
        'job description',
        'job requirements',
        'qualifications',
        'salary',
        'location',

        // Job Applications
        'apply',
        'apply for job',
        'application',
        'job application',
        'submit application',
        'application form',
        'requirements for application',
        'application status',
        'check application status',
        'track application',
        'my applications',
        'submitted applications',
        'withdraw application',
        'cancel application',
        'update application',
        'application update',
        'interview',
        'pending',
        'approved',
        'rejected',

        // Employer Portal / Company
        'employer',
        'employer portal',
        'employer login',
        'company',
        'company profile',
        'company information',
        'company info',
        'post a job',
        'post job',
        'job posting',
        'create job post',
        'add job',
        'edit job',
        'update job posting',
        'close job posting',
        'delete job posting',
        'manage job postings',
        'manage applicants',
        'view applicants',
        'shortlist applicants',
        'applicants',

        // Admin
        'admin',
        'administrator',
        'admin portal',
        'admin login',
        'manage users',
        'manage employers',
        'manage jobseekers',
        'approve jobs',
        'approve employer',
        'verify employer',
        'system settings',
        'reports',
        'dashboard',

        // PESO services / announcements
        'peso',
        'peso services',
        'peso programs',
        'news',
        'updates',
        'announcements',
        'events',
        'job fair',
        'job fairs',
        'hiring events',
        'career guidance',
        'training',
        'training and seminars',
        'seminars',
        'livelihood programs',
    ],

    'fallback_reply' => 'Sorry, I can only assist with PESO Job Portal features like account registration/login, profile/resume updates, job listings/search, job applications/status, employer portal, and admin-related workflows.',
];
