<?php
return function(){
    return [
            'name' => ['page' => 1, 'left' => 10, 'top' => 12, 'width' => 70, 'fontSize' => 12],
            'birthdate' => ['page' => 1, 'left' => 10, 'top' => 18, 'width' => 30, 'fontSize' => 10],
            'sex' => ['page' => 1, 'left' => 60, 'top' => 18, 'width' => 20, 'fontSize' => 10],
            'passport' => ['page' => 1, 'left' => 10, 'top' => 24, 'width' => 35, 'fontSize' => 10],
            'contact' => ['page' => 1, 'left' => 10, 'top' => 30, 'width' => 45, 'fontSize' => 10],
            'email' => ['page' => 1, 'left' => 10, 'top' => 34, 'width' => 55, 'fontSize' => 10],
            'contract' => ['page' => 1, 'left' => 10, 'top' => 50, 'width' => 70, 'fontSize' => 10],
            'narrative' => ['page' => 1, 'left' => 6, 'top' => 60, 'width' => 88, 'fontSize' => 10],
            'civil_status' => ['page' => 1, 'left' => 10, 'top' => 22, 'width' => 45, 'fontSize' => 10],
            'address_abroad' => ['page' => 1, 'left' => 10, 'top' => 38, 'width' => 88, 'fontSize' => 10],
            'address_ph' => ['page' => 1, 'left' => 10, 'top' => 42, 'width' => 88, 'fontSize' => 10],
            'relative_name' => ['page' => 1, 'left' => 10, 'top' => 54, 'width' => 70, 'fontSize' => 10],
            'relative_relationship' => ['page' => 1, 'left' => 10, 'top' => 58, 'width' => 40, 'fontSize' => 10],
            'relative_contact' => ['page' => 1, 'left' => 52, 'top' => 58, 'width' => 42, 'fontSize' => 10],
            'bank_account_no' => ['page' => 1, 'left' => 10, 'top' => 80, 'width' => 30, 'fontSize' => 10],
            'bank_name' => ['page' => 1, 'left' => 42, 'top' => 80, 'width' => 30, 'fontSize' => 10],
            'bank_branch' => ['page' => 1, 'left' => 74, 'top' => 80, 'width' => 20, 'fontSize' => 10],
            'account_name' => ['page' => 1, 'left' => 10, 'top' => 84, 'width' => 60, 'fontSize' => 10],
            'signature_printed' => ['page' => 1, 'left' => 10, 'top' => 90, 'width' => 50, 'fontSize' => 10],
            'help-repatriation' => ['page' => 1, 'left' => 10, 'top' => 52, 'width' => 5, 'fontSize' => 10],
            'help-legal' => ['page' => 1, 'left' => 28, 'top' => 52, 'width' => 5, 'fontSize' => 10],
            'help-medical' => ['page' => 1, 'left' => 46, 'top' => 52, 'width' => 5, 'fontSize' => 10],
            'help-rescue' => ['page' => 1, 'left' => 64, 'top' => 52, 'width' => 5, 'fontSize' => 10],
            'help-welfare_senior' => ['page' => 1, 'left' => 10, 'top' => 56, 'width' => 5, 'fontSize' => 10],
            'help-shipment' => ['page' => 1, 'left' => 28, 'top' => 56, 'width' => 5, 'fontSize' => 10],
            'help-compassionate' => ['page' => 1, 'left' => 46, 'top' => 56, 'width' => 5, 'fontSize' => 10],
            'help-food' => ['page' => 1, 'left' => 64, 'top' => 56, 'width' => 5, 'fontSize' => 10],
            'help-transportation' => ['page' => 1, 'left' => 10, 'top' => 60, 'width' => 5, 'fontSize' => 10],
            'help-temporary_shelter' => ['page' => 1, 'left' => 28, 'top' => 60, 'width' => 5, 'fontSize' => 10],
            'help-others' => ['page' => 1, 'left' => 46, 'top' => 60, 'width' => 30, 'fontSize' => 10],
    ];
};